taskGroups:
- taskSpec:
    runnables:
    - container:
        imageUri: gcr.io/pricewise-huqkr/miraikakaku-batch:latest
        commands: ["python3"]
        arguments: ["massive_full_data_collection.py"]
    computeResource:
      cpuMilli: 4000
      memoryMib: 8192
    maxRetryCount: 2
    maxRunDuration: 14400s  # 4 hours timeout
    environment:
      variables:
        PYTHONUNBUFFERED: "1"
        TZ: "Asia/Tokyo"
  taskCount: 1
  parallelism: 1

allocationPolicy:
  instances:
  - policy:
      machineType: e2-standard-4
      provisioningModel: SPOT
      minCpuPlatform: "Intel Skylake"
  location:
    allowedLocations:
    - regions/us-central1

logsPolicy:
  destination: CLOUD_LOGGING

priority: 50

serviceAccount:
  email: compute@pricewise-huqkr.iam.gserviceaccount.com