apiVersion: batch/v1
kind: Job
metadata:
  name: training-data-generator
  namespace: default
spec:
  parallelism: 4
  completions: 4
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: training-data-generator
    spec:
      restartPolicy: Never
      containers:
      - name: data-generator
        image: gcr.io/effective-shore-r41fc/training-data-generator:latest
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        env:
        - name: DB_HOST
          value: "34.58.103.36"
        - name: DB_USER
          value: "miraikakaku-user"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: "miraikakaku"
        - name: BATCH_SIZE
          value: "125"  # 500銘柄を4並列で処理
        - name: POD_INDEX
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['batch.kubernetes.io/job-completion-index']
        command: ["python3"]
        args: ["/app/parallel_training_data_generator.py"]