steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.batch'
      - '-t'
      - 'gcr.io/effective-shore-r41fc/training-data-generator:latest'
      - '-t'
      - 'gcr.io/effective-shore-r41fc/training-data-generator:$BUILD_ID'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/effective-shore-r41fc/training-data-generator'

# Store images in Google Container Registry
images:
  - 'gcr.io/effective-shore-r41fc/training-data-generator:latest'
  - 'gcr.io/effective-shore-r41fc/training-data-generator:$BUILD_ID'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'