repos:
  # Python code formatting and linting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        files: ^(miraikakakuapi|miraikakakubatch)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^(miraikakakuapi|miraikakakubatch)/.*\.py$
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        files: ^(miraikakakuapi|miraikakakubatch)/.*\.py$
        args: ["--max-line-length=88", "--extend-ignore=E203,W503"]

  # TypeScript/JavaScript linting
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        files: ^miraikakakufront/.*\.(ts|tsx|js|jsx)$
        additional_dependencies:
          - eslint@8.44.0
          - "@typescript-eslint/eslint-plugin@6.0.0"
          - "@typescript-eslint/parser@6.0.0"
          - "eslint-config-next@13.0.0"

  # General code quality
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements

  # Security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        files: ^(miraikakakuapi|miraikakakubatch)/.*\.py$
        args: ["-r", "-x", "*/tests/*"]

  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        files: ^.*Dockerfile.*$