steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miraikakaku-api:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miraikakaku-api:latest'
      - '-f'
      - 'Dockerfile'
      - '.'
    timeout: 900s

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/miraikakaku-api:$BUILD_ID'
    timeout: 600s

  # Deploy to Cloud Run with enhanced configuration
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'miraikakaku-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/miraikakaku-api:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '8080'
      - '--allow-unauthenticated'
      - '--memory'
      - '4Gi'
      - '--cpu'
      - '4'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '20'
      - '--concurrency'
      - '100'
      - '--timeout'
      - '3600'
      - '--set-env-vars'
      - 'ENVIRONMENT=production,API_VERSION=7.0.0,REAL_DATA_ONLY=true,ADVANCED_ML=true,AI_VERSION=2025,API_TIER=PRODUCTION'
      - '--set-cloudsql-instances'
      - '$PROJECT_ID:us-central1:miraikakaku'
      - '--service-account'
      - 'miraikakaku-api@$PROJECT_ID.iam.gserviceaccount.com'
      - '--labels'
      - 'version=real-data-2025,api-type=financial,features=real-data-only,ml-models=xgboost-rf'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s