displayName: "Miraikakaku API Health Check"
httpCheck:
  path: "/health"
  port: 443
  useSsl: true
  requestMethod: "GET"
  validateSsl: true
monitoredResource:
  type: "uptime_url"
  labels:
    host: "miraikakaku-api-465603676610.us-central1.run.app"
timeout: "10s"
period: "300s"
selectedRegions:
  - "USA_OREGON"
  - "USA_VIRGINIA"
  - "ASIA_PACIFIC_SINGAPORE"