steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miraikakaku-frontend:$BUILD_ID'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miraikakaku-frontend:latest'
      - '.'
    timeout: 1800s

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/miraikakaku-frontend:$BUILD_ID'
    timeout: 600s

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'miraikakaku-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/miraikakaku-frontend:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_API_BASE_URL=https://api.miraikakaku.com,NEXT_PUBLIC_FINANCE_API_URL=https://api.miraikakaku.com,API_BASE_URL=https://api.miraikakaku.com'

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

timeout: 3600s