FROM node:18-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8080

# ビルド済みのファイルをコピー
COPY .next/standalone ./
COPY .next/static ./.next/static
COPY public ./public

EXPOSE 8080

CMD ["node", "server.js"]
