# Cloud Monitoring Alert Configuration
# アラート設定の管理

# アップタイムチェック
uptime_checks:
  - name: "miraikakaku-frontend-check"
    display_name: "Miraikakaku Frontend Uptime"
    monitored_resource:
      type: "uptime_url"
      labels:
        host: "www.miraikakaku.com"
        project_id: "pricewise-huqkr"
    http_check:
      path: "/"
      port: 443
      use_ssl: true
      validate_ssl: true
    period: "60s"
    timeout: "10s"
    
  - name: "miraikakaku-api-check"
    display_name: "Miraikakaku API Uptime"
    monitored_resource:
      type: "uptime_url"
      labels:
        host: "api.miraikakaku.com"
        project_id: "pricewise-huqkr"
    http_check:
      path: "/health"
      port: 443
      use_ssl: true
      validate_ssl: true
    period: "60s"
    timeout: "10s"

# アラートポリシー
alert_policies:
  
  # フロントエンド可用性
  - name: "frontend-availability"
    display_name: "Frontend Availability Alert"
    conditions:
      - display_name: "Frontend Uptime Check Failure"
        condition_threshold:
          filter: 'resource.type="uptime_url" AND metric.type="monitoring.googleapis.com/uptime_check/check_passed" AND resource.label.host="www.miraikakaku.com"'
          comparison: "COMPARISON_LT"
          threshold_value: 1.0
          duration: "180s"  # 3分間の失敗で通知
    
  # Cloud Run CPU使用率
  - name: "cloudrun-cpu-usage"
    display_name: "Cloud Run High CPU Usage"
    conditions:
      - display_name: "CPU Utilization > 80%"
        condition_threshold:
          filter: 'resource.type="cloud_run_revision" AND metric.type="run.googleapis.com/container/cpu/utilizations"'
          comparison: "COMPARISON_GT"
          threshold_value: 0.8
          duration: "300s"  # 5分間継続で通知
          aggregations:
            - alignment_period: "60s"
              per_series_aligner: "ALIGN_MEAN"
    
  # Cloud Run メモリ使用率
  - name: "cloudrun-memory-usage"
    display_name: "Cloud Run High Memory Usage"
    conditions:
      - display_name: "Memory Utilization > 90%"
        condition_threshold:
          filter: 'resource.type="cloud_run_revision" AND metric.type="run.googleapis.com/container/memory/utilizations"'
          comparison: "COMPARISON_GT"
          threshold_value: 0.9
          duration: "300s"  # 5分間継続で通知
          aggregations:
            - alignment_period: "60s"
              per_series_aligner: "ALIGN_MEAN"
    
  # Cloud Run リクエストレイテンシ
  - name: "cloudrun-latency"
    display_name: "Cloud Run High Latency"
    conditions:
      - display_name: "Request Latency > 2000ms"
        condition_threshold:
          filter: 'resource.type="cloud_run_revision" AND metric.type="run.googleapis.com/request_latencies"'
          comparison: "COMPARISON_GT"
          threshold_value: 2000
          duration: "180s"  # 3分間継続で通知
          aggregations:
            - alignment_period: "60s"
              per_series_aligner: "ALIGN_PERCENTILE_95"
    
  # Cloud Run エラー率
  - name: "cloudrun-error-rate"
    display_name: "Cloud Run High Error Rate"
    conditions:
      - display_name: "Error Rate > 5%"
        condition_threshold:
          filter: 'resource.type="cloud_run_revision" AND metric.type="run.googleapis.com/request_count" AND metric.label.response_code_class="5xx"'
          comparison: "COMPARISON_GT"
          threshold_value: 0.05
          duration: "300s"  # 5分間継続で通知
          aggregations:
            - alignment_period: "60s"
              per_series_aligner: "ALIGN_RATE"

# 通知チャンネル
notification_channels:
  - type: "email"
    display_name: "Admin Email"
    labels:
      email_address: "yuu.kufs@gmail.com"
  
  # Slack通知を追加する場合
  # - type: "slack"
  #   display_name: "Ops Slack Channel"
  #   labels:
  #     channel_name: "#alerts"
  #     url: "YOUR_SLACK_WEBHOOK_URL"

# アラート調整パラメータ
alert_tuning:
  # 通知の頻度制限
  notification_rate_limit:
    period: "1800s"  # 30分
    
  # 自動解決設定
  auto_close:
    duration: "1800s"  # 30分後に自動クローズ
    
  # 重要度レベル
  severity_levels:
    critical:
      - "frontend-availability"
      - "cloudrun-error-rate"
    warning:
      - "cloudrun-cpu-usage"
      - "cloudrun-memory-usage"
      - "cloudrun-latency"