version: '3.8'

services:
  miraikakaku-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - ENV=production
      - HOST=0.0.0.0
      - PORT=8000
      - LOG_LEVEL=info
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - miraikakaku-network

  miraikakaku-frontend:
    build:
      context: ./miraikakakufront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://miraikakaku-api:8000
    depends_on:
      - miraikakaku-api
    restart: unless-stopped
    networks:
      - miraikakaku-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - miraikakaku-frontend
      - miraikakaku-api
    restart: unless-stopped
    networks:
      - miraikakaku-network

networks:
  miraikakaku-network:
    driver: bridge

volumes:
  logs: